name: Run JMeter Script

on:
  push:
    branches:
      - master

jobs:
  run_jmeter:
    runs-on: ubuntu-latest
    env: 
      Jusers: 20
      Jduration: 300
      Jrampuptime: 40
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
          tar -xzf apache-jmeter-5.4.1.tgz

      - name: Run JMeter Script
        run: |
          cd apache-jmeter-5.4.1/bin
          ./jmeter -n -t ../../Sample_Get_API_Calls_Dynamic.jmx -Jusers=${{env.Jusers}} -Jduration=${{env.Jduration}} -Jrampuptime=${{env.Jrampuptime}} -l ../../test-results.jtl 

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: ./test-results.jtl
